# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/IMGProcess/dvi2vga.xdc

# Block Designs: bd/BRAM_Write/BRAM_Write.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write || ORIG_REF_NAME==BRAM_Write} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_clk_wiz_0/BRAM_Write_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_clk_wiz_0 || ORIG_REF_NAME==BRAM_Write_clk_wiz_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_GND_0/BRAM_Write_GND_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_GND_0 || ORIG_REF_NAME==BRAM_Write_GND_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_VCC_0/BRAM_Write_VCC_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_VCC_0 || ORIG_REF_NAME==BRAM_Write_VCC_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_rgb2vga_0_0/BRAM_Write_rgb2vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_rgb2vga_0_0 || ORIG_REF_NAME==BRAM_Write_rgb2vga_0_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_dvi2rgb_0_0/BRAM_Write_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_dvi2rgb_0_0 || ORIG_REF_NAME==BRAM_Write_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_iobuf_0_0/BRAM_Write_iobuf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_iobuf_0_0 || ORIG_REF_NAME==BRAM_Write_iobuf_0_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_iobuf_1_0/BRAM_Write_iobuf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_iobuf_1_0 || ORIG_REF_NAME==BRAM_Write_iobuf_1_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_processing_system7_0_0/BRAM_Write_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_processing_system7_0_0 || ORIG_REF_NAME==BRAM_Write_processing_system7_0_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_axi_bram_ctrl_0_0/BRAM_Write_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_axi_bram_ctrl_0_0 || ORIG_REF_NAME==BRAM_Write_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/BRAM_Write_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_axi_smc_0 || ORIG_REF_NAME==BRAM_Write_axi_smc_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_axi_bram_ctrl_0_bram_0/BRAM_Write_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==BRAM_Write_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_ImageProcess_0_0/BRAM_Write_ImageProcess_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_ImageProcess_0_0 || ORIG_REF_NAME==BRAM_Write_ImageProcess_0_0} -quiet] -quiet

# IP: bd/BRAM_Write/ip/BRAM_Write_proc_sys_reset_0_0/BRAM_Write_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM_Write_proc_sys_reset_0_0 || ORIG_REF_NAME==BRAM_Write_proc_sys_reset_0_0} -quiet] -quiet

# XDC: bd/BRAM_Write/BRAM_Write_ooc.xdc
