# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_bram_ctrl_0_0/BRAM_Write_axi_bram_ctrl_0_0.xci
# IP: The module: 'BRAM_Write_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_bram_ctrl_0_0/BRAM_Write_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_Write_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_bram_ctrl_0_0/BRAM_Write_axi_bram_ctrl_0_0.xci
# IP: The module: 'BRAM_Write_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_bram_ctrl_0_0/BRAM_Write_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_Write_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
