# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/BRAM_Write_axi_smc_0.xci
# IP: The module: 'BRAM_Write_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/bd_3354.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_5/bd_3354_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_11/bd_3354_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_12/bd_3354_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_6/bd_3354_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_7/bd_3354_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_8/bd_3354_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_9/bd_3354_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_10/bd_3354_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_2/bd_3354_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_3/bd_3354_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_4/bd_3354_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_0/bd_3354_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_1/bd_3354_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_5/bd_3354_s00a2s_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_11/bd_3354_m00s2a_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_6/bd_3354_sarn_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_7/bd_3354_srn_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_8/bd_3354_sawn_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_9/bd_3354_swn_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_10/bd_3354_sbn_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_1/bd_3354_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_1/bd_3354_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_Write_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/BRAM_Write_axi_smc_0.xci
# IP: The module: 'BRAM_Write_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/bd_3354.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_5/bd_3354_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_11/bd_3354_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_12/bd_3354_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_6/bd_3354_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_7/bd_3354_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_8/bd_3354_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_9/bd_3354_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_10/bd_3354_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_2/bd_3354_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_3/bd_3354_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_4/bd_3354_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_0/bd_3354_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_1/bd_3354_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_5/bd_3354_s00a2s_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_11/bd_3354_m00s2a_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_6/bd_3354_sarn_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_7/bd_3354_srn_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_8/bd_3354_sawn_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_9/bd_3354_swn_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_10/bd_3354_sbn_0_ooc.xdc

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_1/bd_3354_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/bd_0/ip/ip_1/bd_3354_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/murakar/xup/embedded/2015_2_zynq_labs/ECE530_final_project/ECE530_final_project.srcs/sources_1/bd/BRAM_Write/ip/BRAM_Write_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM_Write_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
